import "@/app/globals.css";
// import { AdminProvider } from "@/lib/admin-context";
import { AuthProvider } from "@/lib/auth-context";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
